### Exploratory Data Analysis

Understanding the dataset to explore how the data is present in the database and if there is a need of creating some aggregated tables that can help with:

- Vendor selection for profitability
- Product Pricing Optimization

In [11]:
import pandas as pd
import sqlite3

In [12]:
# Create database connection
conn = sqlite3.connect('inventory.db')
conn

In [ ]:
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", conn)
tables

In [ ]:
for table in tables['name']:
    print('-'*50,f'{table}','-'*50)
    print('Count of records:', pd.read_sql(f"select count(*) as count from {table}", conn)['count'].values[0])
    display(pd.read_sql(f"select * from {table} limit 5", conn))

In [11]:
purchases = pd.read_sql_query("select * from purchases where VendorNumber = 4466", conn)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [23]:
purchase_prices = pd.read_sql_query("""select * from purchase_prices where VendorNumber = 4466""", conn)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [13]:
vendor_invoice = pd.read_sql_query("""select * from vendor_invoice where VendorNumber = 4466""",conn)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,None
5,4466,AMERICAN VINTAGE BEVERAGE,2024-02-09,8604,2024-01-24,2024-03-15,347,3261.37,17.61,None
6,4466,AMERICAN VINTAGE BEVERAGE,2024-02-17,8793,2024-02-05,2024-04-02,72,675.36,3.17,None
7,4466,AMERICAN VINTAGE BEVERAGE,2024-03-01,8892,2024-02-12,2024-03-28,117,1096.05,5.15,None
8,4466,AMERICAN VINTAGE BEVERAGE,2024-03-07,8995,2024-02-19,2024-04-02,129,1209.27,5.44,None
9,4466,AMERICAN VINTAGE BEVERAGE,2024-03-12,9033,2024-02-22,2024-04-16,147,1377.87,6.61,None
10,4466,AMERICAN VINTAGE BEVERAGE,2024-03-16,9180,2024-03-03,2024-04-19,211,1979.33,9.50,None
11,4466,AMERICAN VINTAGE BEVERAGE,2024-03-23,9244,2024-03-08,2024-04-21,161,1510.69,6.95,None
12,4466,AMERICAN VINTAGE BEVERAGE,2024-03-31,9371,2024-03-17,2024-05-13,176,1649.20,8.91,None
13,4466,AMERICAN VINTAGE BEVERAGE,2024-04-09,9491,2024-03-24,2024-05-08,215,2016.43,10.08,None
14,4466,AMERICAN VINTAGE BEVERAGE,2024-04-17,9583,2024-03-31,2024-05-12,110,1035.10,5.69,None
15,4466,AMERICAN VINTAGE BEVERAGE,2024-04-20,9639,2024-04-04,2024-06-04,515,5323.01,25.02,None
16,4466,AMERICAN VINTAGE BEVERAGE,2024-04-29,9800,2024-04-15,2024-06-07,275,2775.01,13.60,None
17,4466,AMERICAN VINTAGE BEVERAGE,2024-05-09,9886,2024-04-21,2024-06-12,312,3050.86,13.73,None
18,4466,AMERICAN VINTAGE BEVERAGE,2024-05-14,9999,2024-04-29,2024-06-26,310,3117.82,14.97,None
19,4466,AMERICAN VINTAGE BEVERAGE,2024-05-16,10095,2024-05-06,2024-06-27,215,2123.01,11.46,None
20,4466,AMERICAN VINTAGE BEVERAGE,2024-05-28,10169,2024-05-11,2024-07-04,327,3298.55,15.83,None
21,4466,AMERICAN VINTAGE BEVERAGE,2024-06-04,10257,2024-05-17,2024-07-08,376,3708.18,20.39,None
22,4466,AMERICAN VINTAGE BEVERAGE,2024-06-12,10346,2024-05-23,2024-07-20,640,6458.38,29.71,None
23,4466,AMERICAN VINTAGE BEVERAGE,2024-06-17,10445,2024-05-30,2024-07-19,288,2937.56,15.86,None
24,4466,AMERICAN VINTAGE BEVERAGE,2024-06-22,10600,2024-06-09,2024-08-01,308,3213.28,17.03,None
25,4466,AMERICAN VINTAGE BEVERAGE,2024-06-29,10695,2024-06-16,2024-08-12,143,1585.75,8.09,None
26,4466,AMERICAN VINTAGE BEVERAGE,2024-07-09,10777,2024-06-22,2024-08-15,18,179.88,0.99,None
27,4466,AMERICAN VINTAGE BEVERAGE,2024-07-08,10836,2024-06-25,2024-08-14,8,85.96,0.43,None
28,4466,AMERICAN VINTAGE BEVERAGE,2024-07-11,10969,2024-06-29,2024-08-18,94,993.12,5.06,None
29,4466,AMERICAN VINTAGE BEVERAGE,2024-07-19,11085,2024-07-06,2024-09-04,601,5883.09,31.18,None
30,4466,AMERICAN VINTAGE BEVERAGE,2024-07-26,11187,2024-07-14,2024-08-26,1535,15406.69,77.03,None
31,4466,AMERICAN VINTAGE BEVERAGE,2024-08-03,11244,2024-07-18,2024-09-04,266,2888.22,15.31,None
32,4466,AMERICAN VINTAGE BEVERAGE,2024-08-11,11362,2024-07-26,2024-09-24,206,2171.64,11.08,None
33,4466,AMERICAN VINTAGE BEVERAGE,2024-08-18,11489,2024-08-04,2024-09-16,768,7292.98,37.92,None
34,4466,AMERICAN VINTAGE BEVERAGE,2024-08-24,11540,2024-08-08,2024-10-02,1207,12242.43,64.88,None
35,4466,AMERICAN VINTAGE BEVERAGE,2024-09-02,11716,2024-08-19,2024-09-29,433,4334.43,20.37,None
36,4466,AMERICAN VINTAGE BEVERAGE,2024-09-12,11771,2024-08-23,2024-10-11,370,3640.18,18.20,None
37,4466,AMERICAN VINTAGE BEVERAGE,2024-09-20,11901,2024-09-01,2024-10-30,358,3626.74,16.32,None
38,4466,AMERICAN VINTAGE BEVERAGE,2024-09-25,11993,2024-09-07,2024-10-23,233,2264.85,12.23,None
39,4466,AMERICAN VINTAGE BEVERAGE,2024-10-01,12125,2024-09-16,2024-11-07,284,2813.46,15.47,None
40,4466,AMERICAN VINTAGE BEVERAGE,2024-10-08,12235,2024-09-23,2024-11-20,258,2592.08,11.92,None
41,4466,AMERICAN VINTAGE BEVERAGE,2024-10-09,12253,2024-09-23,2024-11-14,1,11.19,0.05,None
42,4466,AMERICAN VINTAGE BEVERAGE,2024-10-12,12321,2024-09-26,2024-11-19,172,1685.98,7.59,None
43,4466,AMERICAN VINTAGE BEVERAGE,2024-10-20,12466,2024-10-05,2024-11-26,280,2798.60,14.55,None
44,4466,AMERICAN VINTAGE BEVERAGE,2024-10-27,12515,2024-10-09,2024-11-30,178,1763.28,8.64,None
45,4466,AMERICAN VINTAGE BEVERAGE,2024-11-07,12702,2024-10-21,2024-12-11,183,1812.77,8.70,None
46,4466,AMERICAN VINTAGE BEVERAGE,2024-11-12,12752,2024-10-25,2024-12-11,216,2156.16,10.57,None
47,4466,AMERICAN VINTAGE BEVERAGE,2024-11-20,12828,2024-10-30,2024-12-18,262,2597.36,12.99,None
48,4466,AMERICAN VINTAGE BEVERAGE,2024-11-27,12929,2024-11-06,2025-01-04,270,2622.32,12.85,None
49,4466,AMERICAN VINTAGE BEVERAGE,2024-11-28,13092,2024-11-16,2024-12-30,209,2036.17,11.20,None
50,4466,AMERICAN VINTAGE BEVERAGE,2024-12-06,13134,2024-11-20,2025-01-18,305,3018.89,15.70,None
51,4466,AMERICAN VINTAGE BEVERAGE,2024-12-16,13254,2024-11-28,2025-01-13,262,2530.36,11.39,None
52,4466,AMERICAN VINTAGE BEVERAGE,2024-12-26,13432,2024-12-09,2025-01-27,231,2263.43,11.32,None
53,4466,AMERICAN VINTAGE BEVERAGE,2024-12-30,13483,2024-12-13,2025-02-11,221,2178.27,11.33,None
54,4466,AMERICAN VINTAGE BEVERAGE,2025-01-09,13627,2024-12-22,2025-02-05,413,3985.03,19.53,None

In [15]:
sales = pd.read_sql_query("""select *from sales where VendorNo = 4466""",conn)
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-12,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-15,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9448,9_BLACKPOOL_5215,9,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-12-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9449,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-02,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9450,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9451,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9452,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-31,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE

In [19]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [25]:
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE